bin: grimblast show image on copy

diff --git a/.local/bin/grimblast b/.local/bin/grimblast
--- a/.local/bin/grimblast
+++ b/.local/bin/grimblast
@@ -134,13 +134,6 @@ notifyError() {
   fi
 }
 
-resetFade() {
-  if [[ -n $FADE && -n $FADEOUT ]]; then
-    hyprctl keyword animation "$FADE" >/dev/null
-    hyprctl keyword animation "$FADEOUT" >/dev/null
-  fi
-}
-
 killHyprpicker() {
   if [ ! $HYPRPICKER_PID -eq -1 ]; then
     kill $HYPRPICKER_PID
@@ -174,7 +167,6 @@ takeScreenshot() {
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
   else
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
-    resetFade
   fi
 }
 
@@ -228,10 +220,13 @@ elif [ "$SUBJECT" = "area" ]; then
   # shellcheck disable=2086 # if we don't split, spaces mess up slurp
   GEOM=$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp $SLURP_ARGS)
 
+  # reset fade
+  hyprctl keyword animation "$FADE" >/dev/null
+  hyprctl keyword animation "$FADEOUT" >/dev/null
+
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
     killHyprpicker
-    resetFade
     exit 1
   fi
   WHAT="Area"
@@ -243,8 +238,8 @@ else
 fi
 
 if [ "$ACTION" = "copy" ]; then
-  takeScreenshot - "$GEOM" "$OUTPUT" | wl-copy --type image/png || die "Clipboard error"
-  notifyOk "$WHAT copied to buffer"
+  takeScreenshot - "$GEOM" "$OUTPUT" | tee "/tmp/grimblast_copy_file" | wl-copy --type image/png || die "Clipboard error"
+  notifyOk "$WHAT copied to buffer" -i "/tmp/grimblast_copy_file"
 elif [ "$ACTION" = "save" ]; then
   if takeScreenshot "$FILE" "$GEOM" "$OUTPUT"; then
     TITLE="Screenshot of $SUBJECT"
